-- Run this in the Supabase SQL editor to create the analytics tables.
-- sessions and pageviews use UUIDs generated by Postgres (gen_random_uuid()).

create extension if not exists "pgcrypto";

create table if not exists sessions (
  id             uuid primary key default gen_random_uuid(),
  landing_page   text not null,
  referrer       text,
  user_agent     text,
  approx_city    text,
  approx_region  text,
  last_seen_at   timestamptz not null default now(),
  created_at     timestamptz not null default now()
);

create table if not exists pageviews (
  id          uuid primary key default gen_random_uuid(),
  session_id  uuid not null references sessions(id) on delete cascade,
  pathname    text not null,
  created_at  timestamptz not null default now()
);

create index if not exists pageviews_session_id_idx on pageviews(session_id);
create index if not exists sessions_created_at_idx  on sessions(created_at);
